config/routes.rb
HydroFlask::Application.routes.draw do

  resources :netsuite_states

  resources :netsuite_countries

  resources :socials

  ActiveAdmin.routes(self)
 devise_for :accounts
  
  resources :product_translations

  mount Ckeditor::Engine => '/ckeditor'

  resources :stores
  get 'stores/setLatLng' => 'stores#setLatLng'
  get 'socials/update_social' => 'socials#update_social'

  resources :search

  resources :ambassadors

  get '/email_subscriptions/new', :to => 'email_subscriptions#new'
  post '/email_subscriptions/subscribe', :to => 'email_subscriptions#subscribe', :as => 'subscribe_email'
  get '/email_subscriptions/unsubscribe', :to => 'email_subscriptions#unsubscribe', :as => 'unsubscribe_email'
  
  get '/carts/get_shipping', to: 'carts#getShipping';
  get '/carts/update_shipping', to: 'carts#update_shipping';
  get '/carts/update_quantity', to: 'carts#update_quantity';

  resources :donations

  resources :charities
  
  resources :car_related_products

  resources :product_option_value_images

  resources :line_item_options

  resources :related_products

  resources :reviews

  resources :product_option_values

  resources :product_types

  resources :brands

  resources :option_types

  resources :option_values

  resources :options
  
  resources :warranty_submissions
  get "warranty_thankyou" => "warranty_submissions#thanks"
  get "lifetime_warranty" => "warranty_submissions#new"

    resources :accounts
    resources :orders do
      collection do
        get 'confirm'
        post 'confirm'
        post 'payment'
      end
    end

 

  resources :line_items
  post "line_items/create"

  resources :carts

  get "pages/5-back" => "pages#five_back"
  get "pages/hydro-flask-technology" => "pages#hydro_flask_technology"
  get "/hydro-flask-social" => "socials#index"

  get "charities/charity_detail/:id" => "charities#charity_detail"
  get "/donate" => "donations#new"

  resources :category_products
  resources :archive_orders

  resources :products do
    resources :product_images do
      collection do
        get :get_image
      end
    end
  end

  resources :categories

  resources :pages

  root to: 'static_pages#home'
  get '/mycart' => 'carts#show'

  get '/shop' => 'categories#shop'

  get '/:id' => 'pages#show'

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  attr_accessible :description, :featured, :logo, :name
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @charities }
    end
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
    @charity = Charity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @charity }
    end
  end

  def charity_detail
    @charity = Charity.find(params[:id])
    respond_to do |format|
      format.js { render :layout => false }
      format.html { render :layout => false }
    end
  end

  # GET /charities/new
  # GET /charities/new.json
  def new
    @charity = Charity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charity }
    end
  end

  # GET /charities/1/edit
  def edit
    @charity = Charity.find(params[:id])
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(params[:charity])

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render json: @charity, status: :created, location: @charity }
      else
        format.html { render action: "new" }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charities/1
  # PUT /charities/1.json
  def update
    @charity = Charity.find(params[:id])

    respond_to do |format|
      if @charity.update_attributes(params[:charity])
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity = Charity.find(params[:id])
    @charity.destroy

    respond_to do |format|
      format.html { redirect_to charities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_charity.html.erb
<li><a class="charity_link" href="#" charity_id="<%= charity.id %>"><%= charity.name %></a></li>

app/views/charities/_featured_charity.html.erb
<%= image_tag featured_charity.logo, alt: featured_charity.name, title: featured_charity.name %>

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :featured %><br />
    <%= f.number_field :featured %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/charity_detail.html.erb
<div class="charity_detail">
	<%= image_tag @charity.logo, alt: @charity.name, title: @charity.name %>
	<p><%= @charity.description %></p>
</div>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<h1>Listing charities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Logo</th>
    <th>Featured</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @charities.each do |charity| %>
  <tr>
    <td><%= charity.name %></td>
    <td><%= charity.description %></td>
    <td><%= charity.logo %></td>
    <td><%= charity.featured %></td>
    <td><%= link_to 'Show', charity %></td>
    <td><%= link_to 'Edit', edit_charity_path(charity) %></td>
    <td><%= link_to 'Destroy', charity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Charity', new_charity_path %>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @charity.name %>
</p>

<p>
  <b>Description:</b>
  <%= @charity.description %>
</p>

<p>
  <b>Logo:</b>
  <%= @charity.logo %>
</p>

<p>
  <b>Featured:</b>
  <%= @charity.featured %>
</p>


<%= link_to 'Edit', edit_charity_path(@charity) %> |
<%= link_to 'Back', charities_path %>