config/routes.rb
HydroFlask::Application.routes.draw do

  resources :netsuite_states

  resources :netsuite_countries

  resources :socials

  ActiveAdmin.routes(self)
 devise_for :accounts
  
  resources :product_translations

  mount Ckeditor::Engine => '/ckeditor'

  resources :stores
  get 'stores/setLatLng' => 'stores#setLatLng'
  get 'socials/update_social' => 'socials#update_social'

  resources :search

  resources :ambassadors

  get '/email_subscriptions/new', :to => 'email_subscriptions#new'
  post '/email_subscriptions/subscribe', :to => 'email_subscriptions#subscribe', :as => 'subscribe_email'
  get '/email_subscriptions/unsubscribe', :to => 'email_subscriptions#unsubscribe', :as => 'unsubscribe_email'
  
  get '/carts/get_shipping', to: 'carts#getShipping';
  get '/carts/update_shipping', to: 'carts#update_shipping';
  get '/carts/update_quantity', to: 'carts#update_quantity';

  resources :donations

  resources :charities
  
  resources :car_related_products

  resources :product_option_value_images

  resources :line_item_options

  resources :related_products

  resources :reviews

  resources :product_option_values

  resources :product_types

  resources :brands

  resources :option_types

  resources :option_values

  resources :options
  
  resources :warranty_submissions
  get "warranty_thankyou" => "warranty_submissions#thanks"
  get "lifetime_warranty" => "warranty_submissions#new"

    resources :accounts
    resources :orders do
      collection do
        get 'confirm'
        post 'confirm'
        post 'payment'
      end
    end

 

  resources :line_items
  post "line_items/create"

  resources :carts

  get "pages/5-back" => "pages#five_back"
  get "pages/hydro-flask-technology" => "pages#hydro_flask_technology"
  get "/hydro-flask-social" => "socials#index"

  get "charities/charity_detail/:id" => "charities#charity_detail"
  get "/donate" => "donations#new"

  resources :category_products
  resources :archive_orders

  resources :products do
    resources :product_images do
      collection do
        get :get_image
      end
    end
  end

  resources :categories

  resources :pages

  root to: 'static_pages#home'
  get '/mycart' => 'carts#show'

  get '/shop' => 'categories#shop'

  get '/:id' => 'pages#show'

end

app/models/netsuite_country.rb
class NetsuiteCountry < ActiveRecord::Base
  attr_accessible :code, :name
  
  def self.import_command_name
    "get_netsuite_countries"
  end
  
  def self.import_id_column
    :code
  end
  
  def self.import_columns
    [:name]
  end
end

app/controllers/netsuite_countries_controller.rb
class NetsuiteCountriesController < InheritedResources::Base
end

app/helpers/netsuite_countries_helper.rb
module NetsuiteCountriesHelper
end

app/views/netsuite_countries/_form.html.erb
<%= form_for(@netsuite_country) do |f| %>
  <% if @netsuite_country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@netsuite_country.errors.count, "error") %> prohibited this netsuite_country from being saved:</h2>

      <ul>
      <% @netsuite_country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/netsuite_countries/edit.html.erb
<h1>Editing netsuite_country</h1>

<%= render 'form' %>

<%= link_to 'Show', @netsuite_country %> |
<%= link_to 'Back', netsuite_countries_path %>

app/views/netsuite_countries/index.html.erb
<h1>Listing netsuite_countries</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @netsuite_countries.each do |netsuite_country| %>
      <tr>
        <td><%= netsuite_country.code %></td>
        <td><%= netsuite_country.name %></td>
        <td><%= link_to 'Show', netsuite_country %></td>
        <td><%= link_to 'Edit', edit_netsuite_country_path(netsuite_country) %></td>
        <td><%= link_to 'Destroy', netsuite_country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Netsuite country', new_netsuite_country_path %>

app/views/netsuite_countries/new.html.erb
<h1>New netsuite_country</h1>

<%= render 'form' %>

<%= link_to 'Back', netsuite_countries_path %>

app/views/netsuite_countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @netsuite_country.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @netsuite_country.name %>
</p>

<%= link_to 'Edit', edit_netsuite_country_path(@netsuite_country) %> |
<%= link_to 'Back', netsuite_countries_path %>