config/routes.rb
HydroFlask::Application.routes.draw do

  resources :netsuite_states

  resources :netsuite_countries

  resources :socials

  ActiveAdmin.routes(self)
 devise_for :accounts
  
  resources :product_translations

  mount Ckeditor::Engine => '/ckeditor'

  resources :stores
  get 'stores/setLatLng' => 'stores#setLatLng'
  get 'socials/update_social' => 'socials#update_social'

  resources :search

  resources :ambassadors

  get '/email_subscriptions/new', :to => 'email_subscriptions#new'
  post '/email_subscriptions/subscribe', :to => 'email_subscriptions#subscribe', :as => 'subscribe_email'
  get '/email_subscriptions/unsubscribe', :to => 'email_subscriptions#unsubscribe', :as => 'unsubscribe_email'
  
  get '/carts/get_shipping', to: 'carts#getShipping';
  get '/carts/update_shipping', to: 'carts#update_shipping';
  get '/carts/update_quantity', to: 'carts#update_quantity';

  resources :donations

  resources :charities
  
  resources :car_related_products

  resources :product_option_value_images

  resources :line_item_options

  resources :related_products

  resources :reviews

  resources :product_option_values

  resources :product_types

  resources :brands

  resources :option_types

  resources :option_values

  resources :options
  
  resources :warranty_submissions
  get "warranty_thankyou" => "warranty_submissions#thanks"
  get "lifetime_warranty" => "warranty_submissions#new"

    resources :accounts
    resources :orders do
      collection do
        get 'confirm'
        post 'confirm'
        post 'payment'
      end
    end

 

  resources :line_items
  post "line_items/create"

  resources :carts

  get "pages/5-back" => "pages#five_back"
  get "pages/hydro-flask-technology" => "pages#hydro_flask_technology"
  get "/hydro-flask-social" => "socials#index"

  get "charities/charity_detail/:id" => "charities#charity_detail"
  get "/donate" => "donations#new"

  resources :category_products
  resources :archive_orders

  resources :products do
    resources :product_images do
      collection do
        get :get_image
      end
    end
  end

  resources :categories

  resources :pages

  root to: 'static_pages#home'
  get '/mycart' => 'carts#show'

  get '/shop' => 'categories#shop'

  get '/:id' => 'pages#show'

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  attr_accessible :description, :name, :title, :meta_description, :keywords
  friendly_id :name, use: :slugged

  has_many :category_products, dependent: :destroy
  has_many :products, through: :category_products, order: "category_products.order_number"

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json

  caches_page :shop, :show

  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  def shop
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.friendly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<% if category.products.exists? %>
  <h2 id="<%= category.name.gsub(/[ &]/, "") %>"><%= category.name %></h2>
  <% if category_counter == 0 %>
  	<div class="back_to_top">
  		<select name="category_select" id="category_select">
    	 <% Category.all.each do |cat| %>
        <option value="#<%= cat.name.gsub(/[ &]/, "") %>"><%= cat.name %></option>
       <% end %>
  		</select>
  	</div>
  <% else %>
  	<div class="back_to_top"><a href="#">Back to Top</a></div>
  <% end %>
  <div class="category_row">
    <%= render partial: 'product', collection: category.products %>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :meta_description %><br />
    <%= f.text_field :meta_description %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_product.html.erb
 <div class="category_product" <% if (product_counter + 1) % 4 == 1 && product_counter != 0 %>style="clear:both;"<% end %>>
  <div class="product_wrapper">
    <div class="image"><%= link_to image_tag("#{product.product_image.path}small/#{product.product_image.name}", alt: product.name, title: product.name), product_path(product) %></div>
    <h3><%= link_to product.short_name, product_path(product) %></h3>
    <div class="content_wrapper">
      <div class="price"><%= number_to_currency product.price %></div>
      <div class="rating"><%= image_tag "https://s3.amazonaws.com/hydroflask/images/stars_#{product.rating}.png", alt: 'star rating', title: 'star rating' %></div>
    </div>
    <div class="colors" product_id="<%= product.id %>">
      <%= render :partial => 'products/color', :collection => product.product_colors, :locals => {:option_type => ""} %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<table class="admin_table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/shop.html.erb
<div id="category_content">
  <div id="breadcrumb"><%= link_to "Home", root_url %> &raquo; Shop</div>
  <h1>SHOP</h1>
  <a name="top"></a>
  <%= render :partial => 'category', :collection => @categories %>
</div>

app/views/categories/show.html.erb
<div id="category_content">
  <div id="breadcrumb"><%= link_to "Home", root_url %> &raquo; <%= link_to "Shop", shop_url %> &raquo; <%= @category.name %></div>
  <h1 class="cat_header"><%= @category.name %></h1>
	<% if @category.products.exists? %>
  <div class="category_row">
    <%= render partial: 'product', collection: @category.products %>
  <% end %>
</div>